In [1]:
## Ex: 1 - Usando NumPy, importe o dataset iris mantendo o seu conteúdo intacto.


import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [33]:
## Ex: 2 - Extraia a coluna *species* do dataset importado na questão anterior para um vetor unidimensional.


import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

#print(iris) #imprime toda matriz
#iris[:3] #imprime as 3 primeiras linhas 
#iris[:1,3] #imprime 1 linha da 3 coluna 

species = iris[:,4].astype(str)
species




array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [38]:
## Ex: 3 - Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

import numpy as np


iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

##converter as colunas para float
sepallength = iris[:,0].astype(float)

media_sepallength = sepallength.mean()
print ('A media é:',media_sepallength)

mediana_sepallength = np.median(sepallength)
print ('A mediana é:',mediana_sepallength)

desvio_sepallength = np.std(sepallength)
print ('O desvio padrão é:',desvio_sepallength)





A media é: 5.843333333333334
A mediana é: 5.8
O desvio padrão é: 0.8253012917851409


In [36]:
## Ex: 4 - Normalize a coluna (sepallengh) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.

import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallenght', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

##converter as colunas para float
sepallenght = iris[:,0].astype(float)

sepal_lenght_max = sepallenght.max()
sepal_lenght_min = sepallenght.min()

#metodo 1

sepallenght_normalizada = (sepallenght - sepal_lenght_min) / (sepal_lenght_max - sepal_lenght_min)

print (sepallenght[:2])
print (sepallenght_normalizada[:2])



[5.1 4.9]
[0.22222222 0.16666667]


In [39]:
## Ex: 5 - Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallenght', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

##converter as colunas para float
sepallenght = iris[:,0].astype(float)

np.percentile (sepallenght, q=[5,95])






array([4.6  , 7.255])

In [43]:
## Ex: 6. Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:


import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species') 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Quantidade de valores ausentes:",np.isnan(iris_2d[:,0]).sum())
print("Posicao deos valores ausentes:", np.where(np.isnan(iris_2d[:,0])))

Quantidade de valores ausentes: 6
Posicao deos valores ausentes: (array([ 28,  41,  75,  87,  89, 116], dtype=int64),)


In [44]:
## Ex: 7. Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species') 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float' , usecols=[0,1,2,3] , encoding='ascii')

condicao = (iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)
iris_2d[condicao]


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [46]:
## Ex: 8- Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species') 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float' , usecols=[0,1,2,3] , encoding='ascii')

ay_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[ay_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])