In [1]:
## Ex: 1 - Usando NumPy, importe o dataset iris mantendo o seu conteúdo intacto.


import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [33]:
## Ex: 2 - Extraia a coluna *species* do dataset importado na questão anterior para um vetor unidimensional.


import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

#print(iris) #imprime toda matriz
#iris[:3] #imprime as 3 primeiras linhas 
#iris[:1,3] #imprime 1 linha da 3 coluna 

species = iris[:,4].astype(str)
species




array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [38]:
## Ex: 3 - Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

import numpy as np


iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

##converter as colunas para float
sepallength = iris[:,0].astype(float)

media_sepallength = sepallength.mean()
print ('A media é:',media_sepallength)

mediana_sepallength = np.median(sepallength)
print ('A mediana é:',mediana_sepallength)

desvio_sepallength = np.std(sepallength)
print ('O desvio padrão é:',desvio_sepallength)





A media é: 5.843333333333334
A mediana é: 5.8
O desvio padrão é: 0.8253012917851409


In [36]:
## Ex: 4 - Normalize a coluna (sepallengh) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.

import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallenght', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

##converter as colunas para float
sepallenght = iris[:,0].astype(float)

sepal_lenght_max = sepallenght.max()
sepal_lenght_min = sepallenght.min()

#metodo 1

sepallenght_normalizada = (sepallenght - sepal_lenght_min) / (sepal_lenght_max - sepal_lenght_min)

print (sepallenght[:2])
print (sepallenght_normalizada[:2])



[5.1 4.9]
[0.22222222 0.16666667]


In [3]:
## Ex: 5 - Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

import numpy as np

iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallenght', 'sepalwidth', 'petallengh', 'petalwidth', 'species')

iris = np.genfromtxt(iris_dataset_url, delimiter=',', dtype='object', encoding='ascii' )

##converter as colunas para float
sepallenght = iris[:,0].astype(float)

np.percentile (sepallenght, q=[5,95])






array([4.6  , 7.255])

In [43]:
## Ex: 6. Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:


import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species') 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Quantidade de valores ausentes:",np.isnan(iris_2d[:,0]).sum())
print("Posicao deos valores ausentes:", np.where(np.isnan(iris_2d[:,0])))

Quantidade de valores ausentes: 6
Posicao deos valores ausentes: (array([ 28,  41,  75,  87,  89, 116], dtype=int64),)


In [44]:
## Ex: 7. Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species') 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float' , usecols=[0,1,2,3] , encoding='ascii')

condicao = (iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)
iris_2d[condicao]


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [46]:
## Ex: 8- Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species') 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float' , usecols=[0,1,2,3] , encoding='ascii')

ay_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[ay_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
## Ex: 9 - Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species') 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float' , usecols=[0,1,2,3] , encoding='ascii')

iris = np.genfromtxt(url, delimiter =',' , dtype = 'float', usecols=[0,1,2,3])
np.corrcoef(iris[:,0], iris[:,2])[0, 1]


0.8717541573048714

In [7]:
## EX: 10 - Verifique se o vetor iris_2d possui qualquer valor faltante, caso possui deverá retornar True caso contrário False.

# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()


False

In [8]:
## Ex11 - Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

# Entrada

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [9]:
## Ex12 - Encontre e conte os valores únicos da coluna species

# Entrada

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = np.array([linha.tolist()[4] for linha in iris])
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50], dtype=int64))

In [17]:
## Ex13 - Mapeie terceira coluna (petallength) de tal forma que os valores numéricos sejam substituídos por valores textuais, seguindo de acordo com a tabela abaixo:

#Número	Classificação
#Menor do que 3	Pequena
#entre 3 e 5	Média
#Maior ou Igual a 5	Grande

import numpy as np

# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

## Cria os intervalos de petallenght

petal_lenght_intervalos = np.digitize(iris[:, 2].astype('float'),[0,3,5,10])

# Mapeia para respecivas categorias

mapeamento_rotulos = {1: 'Pequeno', 2: 'Medio' , 3: 'Grande' , 4: np.nan}
petal_lenght_categorizada = [mapeamento_rotulos[i] for i in petal_lenght_intervalos]


## Visualiza

petal_lenght_categorizada [:4]

['Pequeno', 'Pequeno', 'Pequeno', 'Pequeno']

In [19]:
## Ex14 - Crie uma nova coluna chamada volume, preenchida com dados resultantes da seguinte equação:

# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#calculo do volume

sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 0].astype('float')

volume = (np.pi * petallength * (sepallength**2))/3

# cria ma nova dimensao
volume = volume [:, np.newaxis]

# Adiciona uma nova coluna com dimensão criada

saida = np.hstack([iris_2d, volume])


In [20]:
## Ex15 - Usando NumPy e o dataset iris responda: Qual é o segundo maior valor de comprimento de pétala (petallength) da espécie setosa?

# Entrada

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

#obtem as colunas species e petallenght
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa' , [2]].astype('float')

# Ordena e pega o segundo maior valor
np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [21]:
## Ex 16 - Ordene o dataset iris com base na coluna sepallength de maneira crescente.

# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Ordena pela coluna na posição 0: sepallength

print(iris[iris[:, 0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


In [22]:
## EX 17 - Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


valores, contagens = np.unique(iris[:, 2], return_counts=True)

print (valores)
print (contagens)
print (valores[np.argmax(contagens)])

[b'1.0' b'1.1' b'1.2' b'1.3' b'1.4' b'1.5' b'1.6' b'1.7' b'1.9' b'3.0'
 b'3.3' b'3.5' b'3.6' b'3.7' b'3.8' b'3.9' b'4.0' b'4.1' b'4.2' b'4.3'
 b'4.4' b'4.5' b'4.6' b'4.7' b'4.8' b'4.9' b'5.0' b'5.1' b'5.2' b'5.3'
 b'5.4' b'5.5' b'5.6' b'5.7' b'5.8' b'5.9' b'6.0' b'6.1' b'6.3' b'6.4'
 b'6.6' b'6.7' b'6.9']
[ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5
  4  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1]
b'1.5'


In [23]:
## Ex 18- Encontre a posição da primeira ocorrência de um valor maior do que 1.0 da quarta coluna (petalwidth) do dataset iris.
# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere (iris[:, 3].astype(float) > 1.0)[0]


array([50], dtype=int64)

In [26]:
## Ex 19 - Obtenha a posição dos top 5 valores maíximos do vetor abaixo:
# Entrada
np.random.seed(100)
vetor = np.random.uniform(1,50, 20)

print (vetor.argsort()) # solução

np.argpartition(-vetor, 5)[:5]  #solucao2




[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]


array([15, 10,  3,  7, 18], dtype=int64)

In [27]:
## Ex 20 - Encontre a média de uma coluna numérica agrupada por uma coluna categórica em uma matriz (vetor numpy 2D)

# Entrada
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Saída Esperada
#>  [[b'Iris-setosa', 3.418],
#>  [b'Iris-versicolor', 2.770],
#>  [b'Iris-virginica', 2.974]] 


coluna_numerica = iris [:, 1].astype('float') #sepalwidth
coluna_categorica = iris [:, 4] #species

saida = []

for categoria in np.unique(coluna_categorica):
    saida.append([categoria, coluna_numerica[coluna_categorica == categoria].mean()])
saida


[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]